### ISSUE TITLE
Why not make MemoryStorage provider Dictionary a ConcurrentDictionary to ensure thread safety.

### ISSUE THREAD

**Issue by aodpi** [Kerego/Storage.Net#1]
https://github.com/Kerego/Storage.Net/blob/e5e05cf78407301f5f68a16486560a23db97683f/Storage.Net/StorageProviders/MemoryStorageProvider.cs#L12

**Comment by Kerego** [comment]
done in 8d5445c5e99a79968c7155eed44d89520887525e
